# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.magnoliaequinevet.com
title: MEVS
email: magnoliaequinevet@gmail.com
author: Kendrick Govan, DVM, DACT
description: 'Magnolia Equine is a mobile veterinary service specializing in onsite veterinary care for the equine community in upstate South Carolina and western North Carolina.'
copyright: 'Copyright &copy; 2020 Magnolia Equine Veterinary Services, LLC. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Get in Touch
    url: https://magnoliaequinevet.com/#contact
